### ISSUE TITLE
NumbaDeprecationWarning with latest dependencies, as "nopython" argument is not supplied to numba.jit

### ISSUE THREAD

**Issue by nandsra21** [blab/pathogen-embed#1]
calling "embed" causes 4 or 5 of the same deprecation warning before any other output is printed. 

Possible fix: 
```
import warnings
warnings.filterwarnings("ignore", message=".*The 'nopython' keyword.*")
```

fix idea from [here](https://github.com/slundberg/shap/issues/2909)

**Comment by huddlej** [comment]
Resolved by https://github.com/blab/pathogen-embed/pull/2/commits/00af5f768f90b80f6adb8da32dd0bc78b7b86245
